### ISSUE TITLE
Simplify the existing instagram page

### ISSUE THREAD

**Issue by SANTHOSH17-DOT** [SANTHOSH17-DOT/attack-vectors-suite#17]
Replace the existing instagram.html file in the PHISHING directory with a simplified version of the Instagram login page. The aim is to reduce the lines of code
[https://github.com/SANTHOSH17-DOT/attack-vectors-suite/blob/main/PHISHING/Instagram.html](url)

**Comment by minicb0** [comment]
i want to work on this issue
