### ISSUE TITLE
Improve Keylogger

### ISSUE THREAD

**Issue by deadex-ng** [SANTHOSH17-DOT/attack-vectors-suite#22]
I would like to add email functionality to the keylogger.
For example: after x minutes, send an email with the key logs.

**Comment by SANTHOSH17-DOT** [comment]
You may go ahead 🚀

**Comment by deadex-ng** [comment]
Great! I'm working on this under Social Winter of Code (SWC) 2023

**Comment by SANTHOSH17-DOT** [comment]
Congratulations @deadex-ng 
Let's do it 🔥
