### ISSUE TITLE
Adding Important keywords to readme.md of shellshock 

### ISSUE THREAD

**Issue by GitWiz01** [SANTHOSH17-DOT/attack-vectors-suite#52]
**Is your feature request related to a problem? Please describe.**
No I it an addon to the readme file to make it more understandable to the reader.

**Describe the solution you'd like**
I would like to add explanation and full forms of some important keywords used while explaining the topic mentioned in readme.

**Please consider this issue**
I would like to work on this further.

**Comment by SANTHOSH17-DOT** [comment]
Thank you for showing your interest. But the readme looks fine already. Could you consider simulating the attack? I've added resources in the issue as well.

**Comment by GitWiz01** [comment]
@SANTHOSH17-DOT Yes I can do that. Assign me the shellshock issue and I'll get back with a Pr of simulation

**Comment by SANTHOSH17-DOT** [comment]
I'm closing this isse
