### ISSUE TITLE
XSS attack vector

### ISSUE THREAD

**Issue by White-rose69** [SANTHOSH17-DOT/attack-vectors-suite#55]
I would like to contribute to this repo by explaining about attack mentioned above. Please assign me this issue under JWOC 2023.
Thank You!

**Comment by SANTHOSH17-DOT** [comment]
@White-rose69 Sure, you may go ahead. Also, could you try to simulate this attack?

**Comment by SANTHOSH17-DOT** [comment]
I'll add the difficulty label once u raise the PR for this issue

**Comment by White-rose69** [comment]
Can I use a lab to simulate the  attack ???

**Comment by SANTHOSH17-DOT** [comment]
Sure @White-rose69

**Comment by White-rose69** [comment]
@SANTHOSH17-DOT I have raised the PR .
Kindly review it
