### ISSUE TITLE
Updaing the SQLi README

### ISSUE THREAD

**Issue by White-rose69** [SANTHOSH17-DOT/attack-vectors-suite#69]
@SANTHOSH17-DOT the SQLi README does not contain enough information so I would like to update it. 
Please assign me this issue.
And could you tell me what should I do with the index.html file as it is just a non working Login page?

**Comment by White-rose69** [comment]
?

**Comment by SANTHOSH17-DOT** [comment]
It needs a functional server with SQL DB that can take an SQL injection

**Comment by White-rose69** [comment]
@SANTHOSH17-DOT I can make a documentation just like I have made for other attacks.
But I will not be able to make that site working.
If the documentation will be fine for you than you can assign me this issue.
Otherwise we'll have to close this one.

**Comment by SANTHOSH17-DOT** [comment]
The document is sufficient for now@White-rose69
