### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by khushimarothi** [SANTHOSH17-DOT/attack-vectors-suite#73]
**Is your feature request related to a problem? Please describe.**
I want to add badges in readme. Please assign under jwoc

![Screenshot (38)](https://user-images.githubusercontent.com/85816852/224638038-fa959fdc-3483-4f2a-867f-dafd27227020.png)

**Comment by SANTHOSH17-DOT** [comment]
@khushimarothi Thank you for showing your interest. But this feature is not required at the moment.

**Comment by SANTHOSH17-DOT** [comment]
@khushimarothi You may go ahead

**Comment by khushimarothi** [comment]
No I feel that it will make the readme look more attractive

**Comment by SANTHOSH17-DOT** [comment]
@khushimarothi Cool. You can work on it
